project_id = "tecnofal"

[api]
enabled = true
port = 55321
schemas = ["public"]
max_rows = 1000

[db]
port = 55322
major_version = 15

[studio]
enabled = true
port = 55323

[auth]
enabled = true
site_url = "http://localhost:5173"
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = false

# Puertos 553xx para convivir con el proyecto "patriona" (que usa los default 543xx).
[analytics]
enabled = false

[inbucket]
port = 55324
